In [1]:
import numpy as np
A=np.array([[10,13,14],[16,17,12],[-12,10,19]])
print(A,type(A))

[[ 10  13  14]
 [ 16  17  12]
 [-12  10  19]] <class 'numpy.ndarray'>


In [5]:
X=A[A>0] 
X

array([10, 13, 14, 16, 17, 12, 10, 19])

In [6]:
X=X[X%2==0]
X

array([10, 14, 16, 12, 10])